In [182]:
import numpy as np
import pandas as pd
df=pd.read_csv("nba_final.csv")

In [183]:
# we are not droping because if is not important so PCA will take care of it and remove it.
df["Pos2"]=df["Pos2"].replace(np.nan,'NONE')
df["Pos2"].unique()

array(['NONE', 'C', 'SG', 'SF', 'PF'], dtype=object)

In [184]:
df=df.fillna(0)

In [185]:
pd.set_option('display.max_columns',500)
df=df.drop(["Player.x",'Player_ID'],axis=1)

In [186]:
from sklearn.preprocessing import LabelEncoder
Le=LabelEncoder()
df['Pos1']=Le.fit_transform(df['Pos1'])
df['Pos2']=Le.fit_transform(df['Pos2'])
df['Tm']=Le.fit_transform(df['Tm'])
df['Season']=Le.fit_transform(df['Season'])
df['Conference']=Le.fit_transform(df['Conference'])
df['Role']=Le.fit_transform(df['Role'])
df['Play']=Le.fit_transform(df['Play'])

In [187]:
X=pd.DataFrame(df.iloc[:,:-1])
Y=pd.DataFrame(df.iloc[:,-1])

In [188]:
from sklearn.preprocessing import StandardScaler
Sts=StandardScaler()
x=Sts.fit_transform(X)

In [115]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,Y,test_size=.30,random_state=29)

In [116]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(X_train,Y_train)

C:\Users\chemi\Desktop\enviroments\myml\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [117]:
Y_predict=LR.predict(X_test)

In [118]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [119]:
accuracy_score(Y_predict,Y_test)

0.9858156028368794

In [120]:
confusion_matrix(Y_predict,Y_test)

array([[403,   5],
       [  1,  14]], dtype=int64)

In [121]:
cr=classification_report(Y_predict,Y_test)
print(cr)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       408
           1       0.74      0.93      0.82        15

    accuracy                           0.99       423
   macro avg       0.87      0.96      0.91       423
weighted avg       0.99      0.99      0.99       423



# PCA

In [237]:
x.shape

(1408, 42)

In [240]:
from sklearn.decomposition import PCA
p=PCA(n_components=.8)
pca_data=p.fit_transform(x)

In [241]:
pca_data.shape

(1408, 11)

In [242]:
p.explained_variance_ratio_.cumsum() # cumsum() is a cumalative sum 

array([0.37517468, 0.48835731, 0.55193246, 0.61095483, 0.6577595 ,
       0.68948533, 0.71995255, 0.74572784, 0.76950198, 0.79292128,
       0.81300355])

In [243]:
p.n_components_

11

In [244]:
pca_data

array([[-4.22171185,  0.40396211,  2.10111589, ..., -0.40266387,
         0.40101782,  0.2491136 ],
       [-2.04983915, -1.99827529,  0.54878226, ...,  0.62310057,
        -0.25356678, -0.75793691],
       [ 2.84299536,  0.24616161, -0.16959082, ...,  0.44931724,
         0.04693342,  0.555316  ],
       ...,
       [-7.12892067, -3.72913226,  4.50163821, ...,  0.08953502,
        -0.74260965,  1.97053706],
       [-1.78465921,  2.02318092,  0.72097949, ..., -0.01534832,
         0.03884485, -0.56686377],
       [-2.56260913, -1.36414077, -0.53083526, ..., -0.14284149,
         0.54621064,  0.10559714]])

In [245]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(pca_data,Y,test_size=.30,random_state=29)

In [246]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(X_train,Y_train)

C:\Users\chemi\Desktop\enviroments\myml\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [247]:
Y_predict=LR.predict(X_test)

In [248]:
accuracy_score(Y_predict,Y_test)

0.983451536643026

In [249]:
confusion_matrix(Y_predict,Y_test)

array([[403,   6],
       [  1,  13]], dtype=int64)

In [250]:
z=classification_report(Y_predict,Y_test)
print(z)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       409
           1       0.68      0.93      0.79        14

    accuracy                           0.98       423
   macro avg       0.84      0.96      0.89       423
weighted avg       0.99      0.98      0.98       423



# LDA

In [297]:
import numpy as np
import pandas as pd
df1=pd.read_csv("nba_final.csv")

In [298]:
# we are not droping because if is not important so PCA will take care of it and remove it.
df1["Pos2"]=df["Pos2"].replace(np.nan,'NONE')
df1["Pos2"].unique()

array([1, 0, 4, 3, 2], dtype=int64)

In [299]:
df1=df.fillna(0)

In [300]:
pd.set_option('display.max_columns',500)
df1=df1.drop(["Player.x",'Player_ID'],axis=1)

KeyError: "['Player.x', 'Player_ID'] not found in axis"

In [301]:
from sklearn.preprocessing import LabelEncoder
Le=LabelEncoder()
df1['Pos1']=Le.fit_transform(df1['Pos1'])
df1['Pos2']=Le.fit_transform(df1['Pos2'])
df1['Tm']=Le.fit_transform(df1['Tm'])
df1['Season']=Le.fit_transform(df1['Season'])
df1['Conference']=Le.fit_transform(df1['Conference'])
df1['Role']=Le.fit_transform(df1['Role'])
df1['Play']=Le.fit_transform(df1['Play'])

In [302]:
X=pd.DataFrame(df1.iloc[:,:-1])
Y=pd.DataFrame(df1.iloc[:,-1])

In [303]:
from sklearn.preprocessing import StandardScaler
Sts=StandardScaler()
xt=Sts.fit_transform(X)

In [304]:
xt.shape

(1408, 42)

In [314]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
LDA= LinearDiscriminantAnalysis(n_components=1) # here n_components is always equal to 1
lda_data=LDA.fit_transform(xt,Y)

C:\Users\chemi\Desktop\enviroments\myml\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [306]:
lda_data.shape

(1408, 1)

In [311]:
LDA.explained_variance_ratio_

array([1.])

In [ ]:
from 